### ISSUE TITLE
Clarification on Readme Example 

### ISSUE THREAD

**Issue by drixie** [mfrachet/server-push-hooks#46]
In the readme example, you have this line: 

`const { data: lastMessage, socket, subscribe, unsubscribe } = useLastMessage(
    "tweet"
  );
`

I would like to know if "data: " is necessary when I use the library, or if that is just specific to the connection with twitter

Also, could you please provide examples of how one may use "socket", "subscribe", and "unsubscribe" in the code?

**Comment by mfrachet** [comment]
`data` is the last message the server has sent concerning the `tweet` event. Does it help?
